apiVersion: v1
kind: Namespace
metadata:
  name: template-rust
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: template-rust-cli
  name: template-rust-cli
  namespace: template-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-rust-cli
  strategy: {}
  template:
    metadata:
      labels:
        app: template-rust-cli
    spec:
      containers:
      - image: ghcr.io/pbar1/template-rust-cli
        name: template-rust-cli
        command:
        - sleep
        - "3600"
        env:
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: http://kube-prometheus-stack-prometheus.monitoring:9090/api/v1/otlp/v1/metrics
        - name: OTEL_METRIC_EXPORT_INTERVAL
          value: "1"
