name: Docker

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push (cli)
      uses: docker/build-push-action@v6
      with:
        file: cli/Dockerfile
        context: .
        platforms: linux/amd64
        build-args: ARCH=x86_64 # FIXME: Can't set dynamically if multiplatform
        push: true
        tags: ghcr.io/pbar1/template-rust-cli:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
